'use strict';
const http=require('node:http');const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');
const ROOT=__dirname;loadEnv();const PORT=Number(process.env.PORT||3000),HOST='0.0.0.0',BASE=(process.env.PUBLIC_BASE_URL||'').replace(/\/$/,''),REDIRECT=process.env.TIKTOK_REDIRECT_URI||`${BASE}/auth/tiktok/callback`,KEY=process.env.TIKTOK_CLIENT_KEY||'',SECRET=process.env.TIKTOK_CLIENT_SECRET||'',SCOPES='user.info.basic,user.info.stats,video.list';
const sessions=new Map(),states=new Map();const configured=Boolean(KEY&&SECRET&&BASE.startsWith('https://')&&REDIRECT.startsWith('https://'));
function loadEnv(){try{for(const line of fs.readFileSync(path.join(__dirname,'.env'),'utf8').split(/\r?\n/)){const m=line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^(["'])(.*)\1$/,'$2')}}catch{}}
function cookies(req){const out={};for(const part of String(req.headers.cookie||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function send(res,status,body,headers={}){res.writeHead(status,{'Cache-Control':'no-store',...headers});res.end(body)}function json(res,status,data){send(res,status,JSON.stringify(data),{'Content-Type':'application/json; charset=utf-8'})}function session(req,res,create=false){const id=cookies(req).taams_sid;let item=id&&sessions.get(id);if(item&&Date.now()-item.touched>30*864e5){sessions.delete(id);item=null}if(!item&&create){const sid=crypto.randomBytes(32).toString('base64url');item={tokens:null,touched:Date.now()};sessions.set(sid,item);res.setHeader('Set-Cookie',`taams_sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000${BASE.startsWith('https://')?'; Secure':''}`);item.id=sid}if(item)item.touched=Date.now();return item}
async function requestJson(url,options={}){const r=await fetch(url,options);let d;try{d=await r.json()}catch{throw Error(`Réponse TikTok invalide (${r.status}).`)}if(!r.ok||d.error&&d.error.code&&d.error.code!=='ok'&&d.error.code!==0)throw Error(d.error_description||d.error?.message||d.message||`TikTok a répondu ${r.status}.`);return d}
async function refreshTokens(item){if(!item?.tokens?.refresh_token)throw Error('Reconnecte ton compte TikTok.');const d=await requestJson('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:KEY,client_secret:SECRET,grant_type:'refresh_token',refresh_token:item.tokens.refresh_token})});item.tokens={...item.tokens,...d,expires_at:Date.now()+Number(d.expires_in||86400)*1000};}
async function validTokens(item){if(!item?.tokens)throw Error('Compte TikTok non connecté.');if(Date.now()>item.tokens.expires_at-60000)await refreshTokens(item);return item.tokens.access_token}
async function apiGetUser(access,fields){return requestJson(`https://open.tiktokapis.com/v2/user/info/?fields=${encodeURIComponent(fields)}`,{headers:{Authorization:`Bearer ${access}`}})}
async function loadTikTokData(item){const access=await validTokens(item);const basic=await apiGetUser(access,'open_id,display_name');let stats={};try{const s=await apiGetUser(access,'follower_count,likes_count,video_count');stats=s.data?.user||{}}catch(err){stats={statsUnavailable:true,statsMessage:err.message}}const vd=await requestJson('https://open.tiktokapis.com/v2/video/list/?fields=id,title,video_description,view_count,like_count,comment_count,share_count,create_time',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify({max_count:20})});const user=basic.data?.user||{};const videos=(vd.data?.videos||[]).map(v=>({title:v.title||v.video_description||'Vidéo TikTok',views:v.view_count||0,likes:v.like_count||0,comments:v.comment_count||0,shares:v.share_count||0}));if(!videos.length)throw Error('TikTok n’a retourné aucune vidéo publique pour ce compte.');return {username:user.display_name||'@TikTok',followers:stats.follower_count||0,followerGrowth:0,period:'20 vidéos récentes',source:'TikTok',videos,statsUnavailable:Boolean(stats.statsUnavailable)}}
function staticFile(res,name){const files={'/':'index.html','/index.html':'index.html','/app.js':'app.js','/style.css':'style.css','/exemple-import.csv':'exemple-import.csv'};const file=files[name];if(!file)return send(res,404,'Introuvable');const p=path.join(ROOT,file);if(!fs.existsSync(p))return send(res,404,'Fichier manquant');const type=file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'text/javascript; charset=utf-8':file.endsWith('.css')?'text/css; charset=utf-8':'text/csv; charset=utf-8';send(res,200,fs.readFileSync(p),{'Content-Type':type})}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');try{
if(req.method==='GET'&&url.pathname==='/api/config')return json(res,200,{configured,httpsRequired:true});
if(req.method==='GET'&&url.pathname==='/api/me'){const s=session(req,res);if(!s?.tokens)return json(res,200,{connected:false});try{return json(res,200,{connected:true,data:await loadTikTokData(s)})}catch(e){return json(res,502,{connected:true,error:e.message})}}
if(req.method==='GET'&&url.pathname==='/auth/tiktok'){if(!configured)return send(res,503,'TikTok n’est pas configuré. Suis le guide README V3.');const s=session(req,res,true),state=crypto.randomBytes(32).toString('hex');states.set(state,{sessionId:s.id,created:Date.now()});for(const [k,v] of states)if(Date.now()-v.created>10*60*1000)states.delete(k);const auth=new URL('https://www.tiktok.com/v2/auth/authorize/');auth.search=new URLSearchParams({client_key:KEY,response_type:'code',scope:SCOPES,redirect_uri:REDIRECT,state}).toString();res.writeHead(302,{Location:auth.toString(),'Cache-Control':'no-store'});return res.end()}
if(req.method==='GET'&&url.pathname==='/auth/tiktok/callback'){if(!configured)return send(res,503,'TikTok n’est pas configuré.');const state=url.searchParams.get('state'),entry=state&&states.get(state);if(!entry||Date.now()-entry.created>10*60*1000){if(state)states.delete(state);return send(res,400,'Connexion expirée ou invalide. Retourne sur TAAMS Analyzer et réessaie.')}states.delete(state);const sid=cookies(req).taams_sid;if(sid!==entry.sessionId)return send(res,400,'Session de connexion invalide. Recommence depuis TAAMS Analyzer.');if(url.searchParams.get('error'))return res.writeHead(302,{Location:'/?error=denied'}).end();const code=url.searchParams.get('code');if(!code)return send(res,400,'TikTok n’a pas renvoyé de code de connexion.');const token=await requestJson('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:KEY,client_secret:SECRET,code,grant_type:'authorization_code',redirect_uri:REDIRECT})});const s=sessions.get(sid);if(!s)return send(res,400,'Session expirée. Recommence la connexion.');s.tokens={...token,expires_at:Date.now()+Number(token.expires_in||86400)*1000};return res.writeHead(302,{Location:'/?connected=1','Cache-Control':'no-store'}).end()}
if(req.method==='POST'&&url.pathname==='/api/disconnect'){if(req.headers.origin&&BASE&&req.headers.origin!==BASE)return json(res,403,{error:'Origine invalide.'});const sid=cookies(req).taams_sid,sidItem=sid&&sessions.get(sid);if(sidItem?.tokens?.access_token&&configured){try{await requestJson('https://open.tiktokapis.com/v2/oauth/revoke/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_key:KEY,client_secret:SECRET,token:sidItem.tokens.access_token})})}catch{}}if(sid)sessions.delete(sid);return json(res,200,{connected:false})}
if(req.method==='GET'&&['/','/index.html','/app.js','/style.css','/exemple-import.csv'].includes(url.pathname))return staticFile(res,url.pathname);
return send(res,404,'Introuvable');
}catch(err){console.error('Request failed:',err.message);if(url.pathname==='/api/me')return json(res,502,{connected:true,error:'Impossible de récupérer les données TikTok. Vérifie les autorisations de l’application puis reconnecte le compte.'});return send(res,500,'Une erreur est survenue. Consulte la configuration V3 et réessaie.')}});
server.listen(PORT,HOST,()=>console.log(`TAAMS Analyzer V3 écoute sur le port ${PORT}.`));
